### PR TITLE
Added reducer tests

### PR DESCRIPTION
**Pull request by giladtamam**

### CODE REVIEW

**Comment by naorye** [comment]
I see you didn't actually tested createPollingActions() method (./actions.js). It should return start and stop actions that should be reflect start and stop action types.
Regarding reducer tests, are you going to add more tests (to achieve full coverage)?

**Comment by giladExelate** [comment]
yep , it's only the beginning of testing  createPollingActions, I will add more when I will have free time.
and I want to add some more reducer tests. you can merge it now, and I will create a new PR or wait till I finish, it's up to you.

**Comment by giladtamam** [comment]
yep , it's only the beginning of testing createPollingActions, I will add more when I will have free time.
and I want to add some more reducer tests. you can merge it now, and I will create a new PR or wait till I finish, it's up to you.

**Comment by giladtamam** [comment]
need to rewrite tests

**Pull request closed without merging**
